db_class_name: 'RedisDatabase' # currently supports MongodbDatabase and RedisDatabase
db_host: 'localhost'
db_port: '6379' # 27017 for mongodb, 6379 for redis
sniff_config: # this configuration is only needed in sniffing mode
  iface: 'en0'
  filter: 'tcp or udp'