db_class_name: '<DB_CLASS_NAME>' # currently supports mongodb(MongodbDatabase) and redis(RedisDatabase)
db_host: '<DB_HOST>'
db_port: '<DB_PORT>'
sniff_config: # this configuration is only needed in sniffing mode
  iface: '<INTERFACE>'
  filter: '<PACKET_FILTER>'
mode: '<MODE>' # mode is one of sniffing, adding_device, delete_aggregated_data, aggregate
time_before: '<TIME_BEFORE>' # time before in seconds, this field is only required in delete_aggregated_data and aggregate mode