db_class_name: '<DB_CLASS_NAME>' # currently supports mongodb(MongodbDatabase) and redis(RedisDatabase)
db_host: '<DB_HOST>'
db_port: '<DB_PORT>'
sniff_config: # this configuration is only needed in sniffing mode
  iface: '<INTERFACE>'
  filter: '<PACKET_FILTER>'
