db_class_name: 'MongodbDatabase' # currently supports MongodbDatabase and RedisDatabase
db_host: 'localhost'
db_port: '27017' # 27017 for mongodb, 6379 for redis
sniff_config: # this configuration is only needed in sniffing mode
  iface: 'en0'
  filter: 'tcp or udp'
mode: 'sniffing' # mode is one of sniffing, adding_device, delete_aggregated_data, aggregate
time_before: 0 # time before in seconds, this field is only required in delete_aggregated_data and aggregate mode